# # MCTS settings
# DIRICHLET_EPSILON = 0.25
# DIRICHLET_ALPHA = 0.3
# SEARCHES = 600
# C = 2
#
# # AlphaZero settings
# TEMPERATURE = 1.25
# BATCH_SIZE = 128
# ITERATIONS = 8
# SELF_PLAY_ITERATIONS = 500
# PARALLEL_GAMES = 100
# EPOCHS = 4

# MCTS settings
DIRICHLET_EPSILON = 0.25
DIRICHLET_ALPHA = 0.3
SEARCHES = 1
C = 2

# AlphaZero settings
TEMPERATURE = 1.25
BATCH_SIZE = 128
ITERATIONS = 8
SELF_PLAY_ITERATIONS = 500
PARALLEL_GAMES = 100
EPOCHS = 4
